# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluateFIS_cpp <- function(inputData, membershipFunctions, ruleConsequents, inputLimits = NULL) {
    .Call(`_FuzzyFishHSRCpp_evaluateFIS_cpp`, inputData, membershipFunctions, ruleConsequents, inputLimits)
}

